language: cpp
script:
- echo TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} &&
  echo TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER} &&
  echo TRAVIS_BRANCH=${TRAVIS_BRANCH} &&
  echo TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} &&
  echo SHELL=$SHELL
- pushd ..
- git clone --depth 200 https://github.com/kees-jan/scroom.git
- cd scroom
- $prefix autoreconf -i
- cd ..
- mkdir scroom-build
- cd scroom-build
- |-
    case $TRAVIS_OS_NAME in
      windows)
        $prefix ../scroom/configure --prefix /c/scroom-installed
        ;;
      *)
        ../scroom/configure --prefix /tmp/scroom-installed
        ;;
    esac
- $prefix make -k -j2 install
- popd
- $prefix autoreconf -i
- mkdir cpp-plugins-build
- cd cpp-plugins-build
- |-
    case $TRAVIS_OS_NAME in
      windows)
        $prefix ../configure CPPFLAGS=-I/c/scroom-installed/include/ LDFLAGS="-L/c/scroom-installed/lib"
        ;;
      *)
        ../configure CPPFLAGS=-I/tmp/scroom-installed/include/ LDFLAGS="-L/tmp/scroom-installed/lib -Wl,-z,defs"
        ;;
    esac
- $prefix make -k -j2 check
- echo "hi" > test.txt
- $prefix curl --data-binary @"./test.txt" -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/octet-stream" "https://uploads.github.com/repos/RoanH/SCROOM-plugin-cpp/releases/v0.0/assets?name=$(basename ./test.txt)"
## - $prefix make -k -j2 distcheck DISTCHECK_CONFIGURE_FLAGS='CPPFLAGS=-I/tmp/scroom-installed/include/ LDFLAGS="-L/tmp/scroom-installed/lib -Wl,-z,defs"'
os:
- linux
- windows
dist: bionic
compiler:
- gcc
addons:
  apt:
    packages:
    - libboost-test-dev
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libgtest-dev
    - google-mock
    - libcairo2-dev
    - libglade2-dev
    - libglib2.0-dev
    - libgtk2.0-dev
    - libtiff5-dev
    - pkg-config
    - doxygen
    - graphviz
git:
  depth: 200
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        $msys2 pacman --sync --noconfirm --needed \
               autoconf \
               automake \
               ccache \
               doxygen \
               git \
               libtool \
               make \
               mingw-w64-x86_64-boost \
               mingw-w64-x86_64-dlfcn \
               mingw-w64-x86_64-gcc \
               mingw-w64-x86_64-glade \
               mingw-w64-x86_64-gtest \
               mingw-w64-x86_64-gtk2 \
               mingw-w64-x86_64-libglade \
               pkg-config \
               zip
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export prefix="$mingw64"
        ;;
      *)
        export prefix=""
    esac
